### ISSUE TITLE
error on make requirements

### ISSUE THREAD

**Issue by aaronsadholz** [edublancas/song-lyrics#34]
Ran into another error here

(py3) dyn-129-236-223-140:song-lyrics spare$ make requirements
echo 'Installing R packages...'
Installing R packages...
./install_r_requirements
Error: unexpected string constant in:
"reqs <- c('tidyverse', 'rjson', 'dplyr', 'ggplot2', 'feather','scales'
          'reshape2'"
Execution halted
make: *** [requirements] Error 1

**Comment by edublancas** [comment]
there was a missing comma, fixed it

**Comment by aaronsadholz** [comment]
working now. thanks
