### ISSUE TITLE
Explaining sentiment score and topic scores

### ISSUE THREAD

**Issue by edublancas** [edublancas/song-lyrics#36]
We are not explaining what sentiment score and topic scores in the interactive component, should we add a small legend somewhere to do so?

**Comment by valmikkpatel** [comment]
We could add it. There will be too much text to add it on the page directly but I could try using a tooltip. 

What should I write there?

**Comment by aaronsadholz** [comment]
If we opt to add this, here is a one sentence description of topic score:

Each artist's topic scores range from 0 to 1, and represent the frequency the artist references that topic relative to other artists.

**Comment by edublancas** [comment]
@aaronsadholz @jose-alvarado-guzman how can we explain the scores in one sentence?

**Comment by edublancas** [comment]
@valmikkpatel maybe add it at the bottom? if you go for the tooltip route, just make sure to hint the user that they can get that by hovering

**Comment by valmikkpatel** [comment]
@edublancas can you also give me a one-liner about how similar artists are found?

**Comment by edublancas** [comment]
We used word embeddings to represent the bag of words as dense vectors, then took the mean vector per artist and computed pairwise distances. Most similar artists are the closest artists by using euclidean distance.

**Comment by valmikkpatel** [comment]
Done
